using MySqlConnector;
using PROY_INMOBILIARIA_malovini.Data;
using PROY_INMOBILIARIA_malovini.Models;
namespace PROY_INMOBILIARIA_malovini.Repositories;

public class InmuebleRepository : IInmuebleRepository
{
  private readonly IUnitOfWork _uow;
  public InmuebleRepository(IUnitOfWork uow) => _uow = uow;
  public async Task<int> Crear(InmuebleModel m) { var c = await _uow.Connection(); const string s = "INSERT INTO inmuebles (imgPortada,cupo,direccion,precio,estado,id_propietario,id_tipo) VALUES (@img,@cupo,@dir,@precio,@estado,@prop,@tipo); SELECT LAST_INSERT_ID();"; await using var x = new MySqlCommand(s, c, _uow.Transaction); Param(x, m); return Convert.ToInt32(await x.ExecuteScalarAsync()); }
  public async Task<bool> Modificar(InmuebleModel m) { var c = await _uow.Connection(); const string s = "UPDATE inmuebles SET imgPortada=@img,cupo=@cupo,direccion=@dir,precio=@precio,estado=@estado,id_propietario=@prop,id_tipo=@tipo WHERE Id=@id"; await using var x = new MySqlCommand(s, c, _uow.Transaction); x.Parameters.AddWithValue("@id", m.Id); Param(x, m); return await x.ExecuteNonQueryAsync() > 0; }
  public async Task<bool> Eliminar(int id) { var c = await _uow.Connection(); await using var x = new MySqlCommand("DELETE FROM inmuebles WHERE Id=@id", c, _uow.Transaction); x.Parameters.AddWithValue("@id", id); return await x.ExecuteNonQueryAsync() > 0; }
  public async Task<InmuebleModel?> ObtenerPorId(int id) { var c = await _uow.Connection(); const string s = "SELECT i.*,t.nombre nombre_tipo,CONCAT(p.nombre,' ',p.apellido) nombre_propietario FROM inmuebles i INNER JOIN tipoinmueble t ON t.id=i.id_tipo INNER JOIN propietarios pr ON pr.id_persona=i.id_propietario INNER JOIN personas p ON p.id=pr.id_persona WHERE i.Id=@id"; await using var x = new MySqlCommand(s, c, _uow.Transaction); x.Parameters.AddWithValue("@id", id); await using var r = await x.ExecuteReaderAsync(); return await r.ReadAsync() ? Map(r) : null; }
  public async Task<IList<InmuebleModel>> ObtenerLista(int paginaNro = 1, int tamPagina = 10) { var c = await _uow.Connection(); const string s = "SELECT i.*,t.nombre nombre_tipo,CONCAT(p.nombre,' ',p.apellido) nombre_propietario FROM inmuebles i INNER JOIN tipoinmueble t ON t.id=i.id_tipo INNER JOIN propietarios pr ON pr.id_persona=i.id_propietario INNER JOIN personas p ON p.id=pr.id_persona ORDER BY i.Id LIMIT @lim OFFSET @off"; await using var x = new MySqlCommand(s, c, _uow.Transaction); x.Parameters.AddWithValue("@lim", tamPagina); x.Parameters.AddWithValue("@off", (paginaNro - 1) * tamPagina); await using var r = await x.ExecuteReaderAsync(); var l = new List<InmuebleModel>(); while (await r.ReadAsync()) l.Add(Map(r)); return l; }
  public async Task<int> ObtenerCantidad() { var c = await _uow.Connection(); await using var x = new MySqlCommand("SELECT COUNT(*) FROM inmuebles", c, _uow.Transaction); return Convert.ToInt32(await x.ExecuteScalarAsync()); }
  private static void Param(MySqlCommand x, InmuebleModel m) { x.Parameters.AddWithValue("@img", (object?)m.ImgPortada ?? DBNull.Value); x.Parameters.AddWithValue("@cupo", m.Cupo); x.Parameters.AddWithValue("@dir", m.Direccion); x.Parameters.AddWithValue("@precio", m.Precio); x.Parameters.AddWithValue("@estado", m.Estado); x.Parameters.AddWithValue("@prop", m.IdPropietario); x.Parameters.AddWithValue("@tipo", m.IdTipo); }
  private static InmuebleModel Map(MySqlDataReader r) => new() { Id = r.GetInt32("Id"), ImgPortada = r.IsDBNull(r.GetOrdinal("imgPortada")) ? null : r.GetString("imgPortada"), Cupo = r.GetInt32("cupo"), Direccion = r.GetString("direccion"), Precio = r.GetDecimal("precio"), Estado = r.GetBoolean("estado"), IdPropietario = r.GetInt32("id_propietario"), IdTipo = r.GetInt32("id_tipo"), NombreTipo = r.GetString("nombre_tipo"), NombrePropietario = r.GetString("nombre_propietario") };
}
